### ISSUE TITLE
[service] modify validation link regex and validation date regex in cadocs_service file

### ISSUE THREAD

**Issue by alfcan** [alfcan/CADOCS_NLU_Model#36]

**Comment by davide-lagamba** [comment]
It was decided to not modify the regex for link validation on this project but to perform this modification on the validation link phase of CADOCS main project, in order to allow an extension of the project in the future without the need to re-modify this project.

**Comment by alfcan** [comment]
Enter the replace of dates from the formats mm.dd.YYYY and mm-dd-YYYY to the format: mm/dd/YYYY

**Comment by kevinpcf** [comment]
The regex is executed even if there is no date.
The regex method should be added in an if.

**Comment by kevinpcf** [comment]
We decided to perform changes on another branch based on branch main.
